import { readFile } from "node:fs/promises";

import { approvedHashFile, currentTestHash, testSafetyDocument } from "./safety-files.ts";

const tokenFlag = process.argv.indexOf("--acknowledge");
const suppliedToken = tokenFlag === -1 ? undefined : process.argv[tokenFlag + 1];
const safetyDocument = await readFile(testSafetyDocument, "utf8");
const expectedToken = safetyDocument.match(/^Acknowledgement token: `([^`]+)`$/m)?.[1];

if (!expectedToken || suppliedToken !== expectedToken) {
  process.stderr.write(`
Refusing to approve the wt test suite.

Read packages/wt/TEST_SAFETY.md in full, then rerun the documented command with its
acknowledgement token.
`);
  process.exitCode = 1;
} else {
  const hash = await currentTestHash();
  await Bun.write(
    approvedHashFile,
    `/** Generated by test/approve-safety.ts after a human or agent reviews TEST_SAFETY.md. */\n` +
      `export const APPROVED_TEST_HASH = "${hash}";\n`,
  );
  process.stdout.write(`Approved reviewed wt test suite hash: ${hash}\n`);
}
