import type { StateStorage } from "zustand/middleware";

import * as api from "@/api/client";

const DEBOUNCE_MS = 500;

/**
 * Nonces generated by this client's store writes. When the server broadcasts
 * a `store_updated` message back, the originating client recognizes its own
 * nonce and skips the redundant reconciliation.
 */
const pendingNonces = new Set<string>();

/** Returns true (and removes the nonce) if this client originated the write. */
export function consumeNonce(nonce: string): boolean {
  return pendingNonces.delete(nonce);
}

/**
 * Create a Zustand-compatible StateStorage that persists to the server's SQLite
 * stores table. On first hydration, migrates from localStorage if the server has
 * no data yet.
 *
 * Each store key maps to a row in the `stores` table. The value is the raw JSON
 * string Zustand persist produces (includes `{ state, version }`).
 */
export function createServerStorage(storeKey: string): StateStorage {
  let debounceTimer: ReturnType<typeof setTimeout> | null = null;

  return {
    getItem: async (name: string): Promise<string | null> => {
      // Try server first
      try {
        const value = await api.getStore(storeKey);
        if (value) return value;
      } catch {
        // Server unreachable — fall through to localStorage
      }

      // Server empty or unreachable — try localStorage migration
      const local = localStorage.getItem(name);
      if (local) {
        try {
          await api.putStore(storeKey, local);
          localStorage.removeItem(name);
        } catch {
          // Migration failed — localStorage stays as fallback
        }
        return local;
      }

      return null;
    },

    setItem: (_name: string, value: string): void => {
      if (debounceTimer) clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        debounceTimer = null;
        const nonce = crypto.randomUUID();
        pendingNonces.add(nonce);
        api.putStore(storeKey, value, nonce).catch(() => {
          // Silently fail — in-memory Zustand state is the source of truth.
          // Next state change will retry.
          pendingNonces.delete(nonce);
        });
      }, DEBOUNCE_MS);
    },

    removeItem: (): void => {
      // No-op: stores are never deleted via Zustand persist
    },
  };
}

/** Pre-built storage instances for each store that uses server persistence. */
export const serverSettingsStorage = createServerStorage("settings");
export const serverKeybindingsStorage = createServerStorage("keybindings");
export const serverUiStorage = createServerStorage("ui");
export const serverToolsBarStorage = createServerStorage("tools-bar");
export const serverSearchStorage = createServerStorage("search");
export const serverWorktreesStorage = createServerStorage("worktrees");
export const serverProjectsStorage = createServerStorage("projects");
